#!/usr/bin/env sh

WIDTH=${WIDTH:-200}
HEIGHT=${HEIGHT:-200}
DATEFMT=${DATEFMT:-"+%a %d.%m.%Y %H:%M:%S"}
SHORTFMT=${SHORTFMT:-"+%H:%M:%S"}

OPTIND=1
while getopts ":f:W:H:" opt; do
    case $opt in
        f) DATEFMT="$OPTARG" ;;
        W) WIDTH="$OPTARG" ;;
        H) HEIGHT="$OPTARG" ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

case "$BLOCK_BUTTON" in
  1|2)
    # Left or middle click - show calendar popup
    posX=$(($BLOCK_X - $WIDTH / 2))
    posY=$(($BLOCK_Y - $HEIGHT - 30))
    i3-msg -q "exec yad --calendar \
        --width=$WIDTH --height=$HEIGHT \
        --undecorated --fixed \
        --close-on-unfocus --no-buttons \
        --posx=$posX --posy=$posY \
        > /dev/null"
    ;;
  3)
    # Right click - open time.is in browser
    xdg-open "https://time.is" &
    ;;
esac

echo "$LABEL$(date "$DATEFMT")"
echo "$LABEL$(date "$SHORTFMT")"
